### ISSUE TITLE
foreign key issue on laravel 5.8, nova 2.0, mariaDB

### ISSUE THREAD

**Issue by matteocapretto** [LifeOnScreen/nova-google2fa#15]
tried to install but it returns 
General error: 1215 Cannot add foreign key constraint (SQL: alter table `user_2fa` add constraint `user_2fa_user_id_foreign` foreign key (`user_id`) references `users` (`id`))
while executing 
php artisan migrate

**Comment by matteocapretto** [comment]
ok it was enough to change migration ill open a pullrequest

**Comment by janicerar** [comment]
I accepted it. Note this will not cover all cases you can always publish migration and override it.
