### ISSUE TITLE
Add possibility to use custom migrations

### ISSUE THREAD

**Issue by ibrunotome** [LifeOnScreen/nova-google2fa#2]
The actual migration doesn't work when user_id is an uuid for example.

**Comment by janicerar** [comment]
I made migrations publishable. Publish migrations and change it. They will now run from your migrations folder.

**Comment by ibrunotome** [comment]
@janicerar will you publish it to the https://novapackages.com ?

**Comment by janicerar** [comment]
@ibrunotome yes, but I will add some features first.
