### ISSUE TITLE
Package Abandoned?

### ISSUE THREAD

**Issue by smartens80** [LifeOnScreen/nova-google2fa#25]
I'm assuming this package is abandoned?

Has anyone made a fork of this which fixes the outstanding issues? In particular, the package doesn't work with PHP 7.4+

Thanks
Scott

**Comment by metalcamp** [comment]
Yes, you can safely assume that this and (all other LifeOnScreen packages) are abandoned. 

As far as I know, nobody from original development team works there anymore and they shut their door as far as development goes.

**Comment by IMPMAC** [comment]
@smartens80 I have found this https://github.com/383Project/nova-google2fa
That along with "pragmarx/google2fa": "^4.0", seems to work

**Comment by smartens80** [comment]
Thanks for the update @IMPMAC - appreciate that.

Running into a few issues, where I'm getting back: -

Error Class 'PragmaRX\Google2FA\Support\Url' not found

Pretty sure this is due to the latest release of pragmarx/google2fa being v8 - and the Url.php file has now been deprecated.

Will have a play with it all and see where I get too.

**Comment by IMPMAC** [comment]
@smartens80 I ran into the same issue, that's why I added `"pragmarx/google2fa": "^4.0"` to composer so it doesn't go over version 4. Add that line and then run `composer update` and it seems to work.

**Comment by smartens80** [comment]
@IMPMAC Ahh yes, that would make sense - I skipped that part of your comment. FYI - I made a fork and changed over to using google2fa-qrcode for the QR code generation. This seems to be working fine with the latest version of pragmarx/google2fa. Reason I did this as I was having issues with HTTP 414 URI Too Long with the current implementation.

For anyone interested, you can see the fork at: - https://github.com/Concept-Affiliates/nova-google2fa

**Comment by anditsung** [comment]
> @IMPMAC Ahh yes, that would make sense - I skipped that part of your comment. FYI - I made a fork and changed over to using google2fa-qrcode for the QR code generation. This seems to be working fine with the latest version of pragmarx/google2fa. Reason I did this as I was having issues with HTTP 414 URI Too Long with the current implementation.
> 
> 
> 
> For anyone interested, you can see the fork at: - https://github.com/Concept-Affiliates/nova-google2fa

Hi, why not create a package for easy instalation?

**Comment by ThisIsMyFavouriteJar** [comment]
> @IMPMAC Ahh yes, that would make sense - I skipped that part of your comment. FYI - I made a fork and changed over to using google2fa-qrcode for the QR code generation. This seems to be working fine with the latest version of pragmarx/google2fa. Reason I did this as I was having issues with HTTP 414 URI Too Long with the current implementation.
> 
> For anyone interested, you can see the fork at: - https://github.com/Concept-Affiliates/nova-google2fa

I followed the installation instructions but nothing shows up. Any idea how I can get the package in your link to work for me?

**Comment by smartens80** [comment]
@AbetaNL Did you set `'enabled' => env('OTP_ENABLED', true),` in the `config\google2fa.php` file?
