### ISSUE TITLE
Option to override User2fa model

### ISSUE THREAD

**Issue by ibrunotome** [LifeOnScreen/nova-google2fa#9]
Hi @janicerar, can you please make an option to override the User2fa model? This way we can set a custom `$connection` on the User2fa model.

I think this will take time, so if you can just make a release for now with just the User2fa with a `$connection` reading from the `lifeonscreen2fa.php` would help a lot!

And one more thing, doesn't affect anything but I think that the annotations from the User2fa model aren't updated.

**Comment by janicerar** [comment]
Hi @ibrunotome,

I make support to override User2fa model. You can specify a path in the config.
I push the solution to the development branch, can you check if this works for you.

Tnx for annotations notice.

**Comment by ibrunotome** [comment]
Hi @janicerar, this was very fast and it worked!

**Comment by janicerar** [comment]
It was tagged v1.0.1
